### PR TITLE
initialize ExpireTime as a number, not string

### PR DESCRIPTION
**Pull request by stephankn**
fix database insertion problem in #13

### CODE REVIEW

**Comment by mikedlr** [comment]
@stephankn is there any chance you could write some kind of test case (unit/functional anything) to demonstrate the problem and how the patch fixes it?  This is a codebase that will have to be taken over by people who are new to it so it's really helpful to have something which explains what was wrong before.

**Comment by stephankn** [comment]
in #13 a user was able to reproduce the issue. My patch is solely based on source code reading.
The variable $ExpireTime is initialized as a empty string. And without further assignment, it never gets a numeric value.
The insert statement then gets a '' to insert into a BIGINT column. 

This will result in an error with mariadb releases 10.2.4 and newer. I guess the server got an update which made this problem now visible. In earlier versions, the value was converted to either 0 or NULL.
https://mariadb.com/kb/en/sql-mode/#strict-mode

All usage of the $ExpireTime which is reading from the DB is checking for numeric values greater than now() in epoch seconds.
So writing a 0 for undefined sounds like this is the desired value.

Let me know if you need further reproduction cases. I have not seen unit tests or other tests as part of the repository, So there is no way to have automated checks in a build pipeline.
A demo would demonstrate that the database strict setting is working as observed by initial report in #13.

**Review by eegeeZA — APPROVED** [review]
My knowledge of Perl is limited, but this minor change look fine. As @mikedlr said, it would be good to have tests. If @ashemsay could confirm this fix, that would also be fine.

Double-check `$mexpiretime` which appears to also be initialised as a string and used in other parts to `getExpireTime` when setting `$ExpireTime`.

**Comment by stephankn** [comment]
@eegeeZA 
all the variables m-something like $mexpiretime are used to read data from the message. They represent strings and should so be initialized as empty string.

**Comment by stephankn** [comment]
As you asked for demo:

prepare database as in sql file in this repository. Execute demo script, which does two inserts. One fails, due to strict mode.

```
 # perl demo.pl
trying to insert empty string:
DBD::mysql::st execute failed: Incorrect integer value: '' for column 'ExpireTime' at row 1 at demo.pl line 38.
trying to insert 0
demo done.
```

File contents:
```perl
#!/bin/perl

# CREATE TABLE `Emails` (
#  `EmailID` bigint(20) NOT NULL AUTO_INCREMENT,
#  `UserID` bigint(20) NOT NULL DEFAULT '0',
#  `Prefix` varchar(20) DEFAULT NULL,
#  `Word` varchar(20) NOT NULL DEFAULT '',
#  `InitialCount` tinyint(4) NOT NULL DEFAULT '0',
#  `Count` tinyint(4) NOT NULL DEFAULT '0',
#  `TimeAdded` bigint(20) DEFAULT NULL,
#  `Sender` varchar(254) DEFAULT NULL,
#  `Address` text,
#  `DeliveryAddress` varchar(255) DEFAULT '',
#  `Hidden` tinyint(4) NOT NULL DEFAULT '0',
#  `Note` varchar(254) DEFAULT NULL,
#  `PrivateHash` varchar(50) NOT NULL DEFAULT '',
#  `NumForwarded` bigint(20) NOT NULL DEFAULT '0',
#  `NumDeleted` bigint(20) NOT NULL DEFAULT '0',
#  `ExpireTime` bigint(20) unsigned DEFAULT NULL,
#  PRIMARY KEY (`EmailID`),
#  KEY `UserID` (`UserID`,`Word`,`Count`),
#  KEY `Word` (`Word`)
#) ENGINE=MyISAM AUTO_INCREMENT=8443939 DEFAULT CHARSET=latin1;



use DBD::mysql;

$ExpireTime_s = '';
$ExpireTime_n = 0;

$db = DBI->connect("DBI:mysql:database=dbname;host=localhost","demo","demo");

$sql = "INSERT INTO Emails (ExpireTime) VALUES (?)";
$st = $db->prepare($sql);

print("trying to insert empty string:\n");
$st->execute($ExpireTime_s);

print("trying to insert 0\n");
$st->execute($ExpireTime_n);

print("demo done.\n");
```

**Comment by eegeeZA** [comment]
Thanks for the demo file.

@mikedlr anything more required? Otherwise we can merge this PR.

**Comment by ashemsay** [comment]
> My knowledge of Perl is limited, but this minor change look fine. As @mikedlr said, it would be good to have tests. If @ashemsay could confirm this fix, that would also be fine.
> 
> Double-check `$mexpiretime` which appears to also be initialised as a string and used in other parts to `getExpireTime` when setting `$ExpireTime`.

I can confirm it works

**Comment by eegeeZA** [comment]
Cool, going to merge this. Thanks for the PR.

**Pull request merged**
