### PR TITLE
Final code dump from website

### PR DESCRIPTION
**Pull request by eegeeZA**
While updating the code, I had to manually exlude the changes from PR #1 as they were not in the archive downloaded off the website. That’s weird since the forum post said that the code on SourceForge was practically up-to-date.

```
Downloaded from http://www.spamgourmet.com/sg.tgz
SHA-256: 80C763199A1204E3916CBDDDD291AB6370B7D0DFA1A6CAEB3FF12210FBAD0A07

Excluded changes that were added to `mailhandler/spameater` preventing
spoof attempts. The code was extracted from
https://bbs.spamgourmet.com/viewtopic.php?
f=5&t=1785&sid=e8ee7853d8bb33db94a857cdc3becbba#p8200
```

### CODE REVIEW

**Comment by jgonggrijp** [comment]
What's next? Review? How to review such a big change? Maybe a multi-person effort? Maybe only the part that you manually excluded?

**Comment by eegeeZA** [comment]
That's the tricky part, since I couldn't recreate the commits from the SVN file. One way might be to redo the same thing I did and see if you arrive at the same result. The more people that review and confirm, the better.

All did was essentially:
1. Remove all existing files
2. Extract the tar-gzip to the root
3. Ignore all the `.svn` folders

**Comment by jgonggrijp** [comment]
Ah that makes sense. Good idea.

Unfortunately, I'm stuck with a tiny laptop until March 23, so I probably won't try this before then. If other people can help out in the meanwhile and you feel confident enough, please don't wait for me.

**Comment by jgonggrijp** [comment]
I'm not stuck with a tiny laptop anymore, but I won't get to it today. Maybe Friday, March 27. In the meanwhile, everyone else: please don't hold back and give it a try!

**Comment by jgonggrijp** [comment]
@eegeeZA Sorry for the long silence. Please go ahead and merge it if you prefer this over waiting any longer. We can even review it after the fact.

Alternatively, at your option, I am also still willing to try this before you merge, but I won't be able to do it before the end of this week.

**Comment by eegeeZA** [comment]
No worries, I thought it might be good close this off in case it gets forgotten. I'm happy to leave it open for longer if you or anyone else would like to review.

**Comment by jgonggrijp** [comment]
Well as you said, the more people review and confirm, the better. I never really forgot about this and I still intended to review it, but it got buried under other things. Let's see whether I can give this a little more priority.

**Review by mikedlr — APPROVED** [review]
There's far too much to effectively review here, however since we understand that this is the move towards the correct state of Spamgourmet's code as deployed we should merge this urgently, and attempt to move forward from there.  There are clearly things that are outdated so adding some warnings in a coming PR would be worthwhile.

**Comment by jgonggrijp** [comment]
@mikedlr You are absolutely right. *In general* reviewing is desirable, but given that this particular PR just updates the code to reflect what's actually running, there's not much to discuss about it. Sorry @mikedlr and @eegeeZA for causing delay.

**Comment by eegeeZA** [comment]
Cool, then I am going to merge this PR. Thanks @mikedlr for creating #12 to track the outdated code.

**Pull request merged**
